# Generated by Django 5.1.3 on 2024-11-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=4)),
                ('owner_email', models.EmailField(max_length=254)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.controlador')),
            ],
        ),
    ]
